### PR TITLE
19JUN2021 Initial Pull from Dev Branch

### PR DESCRIPTION
**Pull request by mdrammeh1**

### CODE REVIEW

**Review by willywil548 — CHANGES_REQUESTED** [review]
That isn't the way this works.

**Comment by willywil548** [comment]
Contact me if your DSO liaison cannot help you. We'll do a call and walk-through but first please review the video series from: https://teams.microsoft.com/_#/files/General?threadId=19%3A029001df96f442aa80243a05e47227f5%40thread.tacv2&ctx=channel&context=How-To-Videos&rootfolder=%252Fsites%252FUMGCSWEN670SUMMER2021%252FShared%2520Documents%252FGeneral%252FHow-To-Videos

**Comment by aydot4life2009** [comment]
Adding file operations read and write file to the project

**Comment by willywil548** [comment]
Wrong direction. Do not create PR to open a branch locally.

From command line: git checkout developer_drammeh

Then: git pull origin main

**Pull request closed without merging**
